### PR TITLE
Add android javadoc 0.2

### PR DESCRIPTION
**Pull request by matteblair**
This adds the generated javadoc for version 0.2 of the Tangram Android SDK. Javadoc JARs are available with each release through maven central but hosting the pages here via github.io allows a more explore-able and browse-able format.

### CODE REVIEW

**Comment by matteblair** [comment]
Gonna go ahead and merge this so I can test whether this works the way I expect. Forgive my brazen abuse of commit privileges.

**Comment by tallytalwar** [comment]
No worries, will review it right now also.

**Comment by tallytalwar** [comment]
[These](https://htmlpreview.github.io/?https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/android-sdk/0.2/index.html) look good to me. 

I am not sure if the intent was not to get the javadoc styling? (as has been discussed for a couple of days). But for a first pass these look good.

**Comment by meetar** [comment]
:+1:

**Pull request merged**
