### PR TITLE
Add "centroid" draw parameter

### PR DESCRIPTION
**Pull request by matteblair**
This seems to be a thing: https://github.com/tangrams/tangram/blob/master/src/styles/points/points.js#L212

### CODE REVIEW

**Comment by meetar** [comment]
Nice, thanks!

**Comment by matteblair** [comment]
Cool. Wasn't sure if this is an experimental part of the spec, but if it's something we feel like keeping then tangram-es can support it too.

**Comment by bcamper** [comment]
It is a thing... I'm not sure we want to keep the current behavior
ultimately, but that's what it does now :)

On Tue, Sep 29, 2015 at 12:17 PM, Peter Richardson <notifications@github.com

**Comment by bcamper** [comment]
I think we should probably figure out our approach to things like highway
shields (that have to be intelligently "placed" along lines or polygons)
before we totally commit.

**Pull request merged**
