### PR TITLE
Add API docs for tangram-es 0.6.1

### PR DESCRIPTION
**Pull request by matteblair**
Aside: Most of the docs are unchanged from one release to another, but we've been duplicating the whole set of doc pages anyway. I wonder if the size of all these pages will be a problem in the future?

### CODE REVIEW

**Comment by tallytalwar** [comment]
> I wonder if the size of all these pages will be a problem in the future?

Me and @meetar have discussed this scenario, and we decided on deprecating/deleting older version docs if we hit a size issue in future.

**Comment by nvkelso** [comment]
FWIW: For Tilezen docs I only rely on Github release versioning to track the state of docs for particular releases.

**Comment by tallytalwar** [comment]
We are still pointing to `0.5.1` docs in the mapzen documentation. @matteblair can you rebase this and merge it.

**Comment by matteblair** [comment]
Rebased now, should be good to go!

**Review by tallytalwar — APPROVED** [review]

**Pull request merged**
